apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: llama-base-template
  title: Llama Base Template
  description: Scaffold a new service from llama_base_template
spec:
  owner: your-team
  type: service

  parameters:
    - title: Service Details
      required:
        - name
      properties:
        name:
          type: string
          title: Project Name
        description:
          type: string
          title: Project Description

  steps:
    - id: fetch-template
      name: Fetch Template from GitHub
      action: fetch:template
      input:
        url: https://github.com/PyContriver/llama_base_template/archive/main.zip
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=PyContriver&repo=${{ parameters.name }}
        defaultBranch: main
        protectDefaultBranch: true
        description: ${{ parameters.description }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
